### PR TITLE
Complete app tests

### PR DESCRIPTION
**Pull request by jeaunrg**
these modifications should work to test interface

### CODE REVIEW

**Comment by Hboni** [comment]
It seems it is not working, did it work locally for you @jeaunrg?

**Comment by jeaunrg** [comment]
No it doesnt work but I figured it out while sleeping, I will fix the issue today

**Comment by jeaunrg** [comment]
I dont know why but it seems that the qtbot need the reference to the connector inside the app, 
unless it wont consider the connector and the link between buttons and functions will not work.

**Comment by Hboni** [comment]
Oooooh nice! It explains why clicking on button did not trigger the connection method! Good job!
Is it a problem for the application to have the connector linked to the MainWindow? It seems a little bit logical for me, but did you see some PyQt code organization examples with the organization that you made with Connector?

**Comment by jeaunrg** [comment]
No I don't find other example with that type of organization. Generally PyQt app with an MVC structure seems to have a class **app** which define the three class: controller, view and model. 
- The **view** send signal to the **controller** and receive signal from the **model**.
- The **controller** receive signal from the **view** set data in the **model**.
- The **model** do processes and send changed signal to the **view**.

The way I organized the code was to have 2 fully independant part (view and core can work separately) and the controller do all the connections between the view and the model, both ways.

In hindsight I prefer the classical MVC way but we should merge the current branches before this big modification.
Do you think we should modify the code to fit the classical MVC? Or do you have another method in mind?

**Comment by Hboni** [comment]
I do not have the use to create an MVC organization, so what you saw seems good, maybe we can try one time to migrate to another code organization.
It was only to know if the organization that you deployed was common or not

**Comment by jeaunrg** [comment]
![CFbNC](https://user-images.githubusercontent.com/57048964/115085651-250d0900-9f0b-11eb-9745-a20565a5c1b1.png

**Comment by jeaunrg** [comment]
CFbNC
I was wrong, Im using a Model-View-Presenter...

**Comment by jeaunrg** [comment]
sorry I didnt mean to close the pull request 😅 improper handling

**Comment by Hboni** [comment]
I think that if you use an MVP instead of an MVC, it is not a problem, just knowing what is implemented and use it at its best is important.
Even with what you find, do you think that it will be necessary to move to an MVC later?

**Comment by jeaunrg** [comment]
No MVC is outdated, now everyone seems to use MVP or MVVM.

**Review by Hboni — APPROVED** [review]

**Review by Hboni — CHANGES_REQUESTED** [review]
I am working on completing tests, do not merge now :/ I will finish it today

**Review by Hboni — APPROVED** [review]
@jeaunrg if you can look at new tests before merging, it would be great!

**Pull request merged**
